# app/config/security.yml
security:
    firewalls:
        frontend:
          pattern: ^/*
          anonymous: ~
          form_login: 
            login_path: /alumno/login
            check_path: /alumno/login_check
    access_control:
        - { path: ^/alumno/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/alumno/registrar, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/alumno/*, roles: ROLE_USUARIO }
    providers:
        alumnos:
            entity: { class: Hazzard\Bundle\CursoBundle\Entity\Alumno, property: dni }
    encoders:
        Hazzard\Bundle\CursoBundle\Entity\Alumno: { algorithm: sha512, iterations: 10 }